[tool]
[tool.poetry]
name = "icalstatus"
version = "0.0.5"
description = "icalstatus"
license = "ISC"
classifiers = ["Development Status :: 4 - Beta", "Topic :: Utilities", "License :: OSI Approved :: ISC License (ISCL)"]
homepage = "https://github.com/frbor/icalstatus"
authors = ["Fredrik Borg <fredrikb.borg@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
icalstatus = "icalstatus.status:status"
icalwaybar = "icalstatus.status:waybar"
icalparse = "icalstatus.parse:main"

[tool.poetry.dependencies]
python = "^3.9.0"
caep = "^0.1.8"
requests = "^2.28.1"
recurring-ical-events = "^2.0.0"
icalendar = "^5.0.0"
pytz = "*"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
pytest = "^7.3.1"
pre-commit = "^3.3.1"
ruff = "^0.0.267"
mypy = "^1.2.0"
types-requests = "*"
types-python-dateutil = "*"
types-pytz = "*"

[tool.mypy]
strict = true

[tool.ruff]
# pyflakes, pycodestyle, pyupgrade and isort
select = ["F", "E", "W", "UP", "I001"]

target-version = "py39"
